# Pandas Tutorial

Combined notebook covering Pandas input/output, column operations, missing values, row iteration, and time-series data.


# Python Pandas Input-Output

# Python Pandas I/O
### Creating DataFrames, Reading and Writing to CSV & JSON files  
[Documentation](https://pandas.pydata.org/docs/index.html)

In [1]:
import numpy as np
import pandas as pd
import random

### Creating DataFrames from Lists and Dicts
▶ New DataFrame from a **List**  
Pandas automatically assigns numerical row indexes.

In [2]:
data1 = [random.random() for i in range(10000)]
df = pd.DataFrame(data1)
df.head()

          0
0  0.027684
1  0.174996
2  0.743153
3  0.628041
4  0.658552

▶ New DataFrame from a **2D List**  
Column names default to integers. Each subList is a row.

In [3]:
data2 = [[i, random.randint(10,99)] for i in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ']
df = pd.DataFrame(data2)
df.head()

   0   1
0  A  28
1  B  78
2  C  85
3  D  65
4  E  98

▶ New DataFrame from a **Dictionary**  
Dict Keys become column names

In [4]:
data3 = {
    'Model':['T57','T61','T64','T65'],
    'Price':[1.42,1.48,1.73,1.95],
    'Size':['57 inches','61 inches','64 inches','65 inches']}
df = pd.DataFrame(data3)
df

  Model  Price       Size
0   T57   1.42  57 inches
1   T61   1.48  61 inches
2   T64   1.73  64 inches
3   T65   1.95  65 inches

Change previous example to use Model number as index.

In [5]:
df = pd.DataFrame(
    {'Price':data3['Price'],'Size':data3['Size']}, 
    index=data3['Model'])
df

     Price       Size
T57   1.42  57 inches
T61   1.48  61 inches
T64   1.73  64 inches
T65   1.95  65 inches

▶ New DataFrame from a List of Dictionaries  
Note, missing Length is populated with NaN (not a number).

In [6]:
data4 = [
    {'Ht':63, 'Len':45, 'Wt':2.6}, 
    {'Ht':29, 'Wt':1.7},
    {'Ht':37, 'Len':71, 'Wt':4.2}]
df = pd.DataFrame(data4)
df

   Ht   Len   Wt
0  63  45.0  2.6
1  29   NaN  1.7
2  37  71.0  4.2

### Reading & Writing DataFrames to CSV Files
[Documentation](https://pandas.pydata.org/docs/user_guide/io.html#csv-text-files) of numerous optional parameters.  

▶ Write DataFrame to CSV file

In [7]:
df = pd.DataFrame(data4)
df.to_csv('outfile.csv', index=False) #, sep=';')

▶ Read CSV file into DataFrame  
Missing numerical data are given value NaN by default.

In [8]:
df = pd.read_csv('outfile.csv')
df

   Ht   Len   Wt
0  63  45.0  2.6
1  29   NaN  1.7
2  37  71.0  4.2

▶ Convert DataFrame to_string

In [9]:
df = pd.DataFrame(data4)
d4str = df.to_string()
d4str

'   Ht   Len   Wt\n0  63  45.0  2.6\n1  29   NaN  1.7\n2  37  71.0  4.2'

### Reading & Writing DataFrames to JSON files
[Documentation](https://pandas.pydata.org/docs/user_guide/io.html#csv-text-files) of numerous optional parameters.  

▶ Convert DataFrame to **JSON** string  
No argument - json by columns is default, {column -> {index -> value}}

In [10]:
data4_json = df.to_json()
data4_json

'{"Ht":{"0":63,"1":29,"2":37},"Len":{"0":45.0,"1":null,"2":71.0},"Wt":{"0":2.6,"1":1.7,"2":4.2}}'

Use orient='index' to structure the json by rows, {index -> {column -> value}}.  
You can also strip out the row indices by using orient='records'.

In [11]:
data4_json = df.to_json(orient='index')
data4_json

'{"0":{"Ht":63,"Len":45.0,"Wt":2.6},"1":{"Ht":29,"Len":null,"Wt":1.7},"2":{"Ht":37,"Len":71.0,"Wt":4.2}}'

▶ Write to a text file in JSON format.

In [12]:
data4_json = df.to_json('outjson.txt')
data4_json

▶ Read same JSON data back in to a DataFrame.

In [13]:
data4 = pd.read_json('outjson.txt')
data4

   Ht   Len   Wt
0  63  45.0  2.6
1  29   NaN  1.7
2  37  71.0  4.2


# Pandas - Change Column Names

# Pandas - Change Column Names

In [1]:
import pandas as pd

In [7]:
df = pd.read_csv('iris.data', names=['A','B','C','D','Label'])
df

       A    B    C    D           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

axis=1 tells Pandas it's column names.  
inplace=True tells Pandas to save the changes to our DataFrame.

In [8]:
df.rename({'A':'aa', 'B':'bb'}, axis=1, inplace=True)
df

      aa   bb    C    D           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]


# Pandas Reorder Columns in DataFrame

# Pandas - Reorder Columns
Swap two columns, or change the order of columns

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.data', names=['A','B','C','D','Label'])
df

       A    B    C    D           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

1) get a list of the column names.

In [3]:
titles = list(df.columns)
titles

['A', 'B', 'C', 'D', 'Label']

2) Swap or move whatever columns you want in the list.

In [4]:
titles[1], titles[2] = titles[2], titles[1]
titles

['A', 'C', 'B', 'D', 'Label']

3) Reassign the columns in the DataFrame.

In [5]:
df = df[titles]
df

       A    C    B    D           Label
0    5.1  1.4  3.5  0.2     Iris-setosa
1    4.9  1.4  3.0  0.2     Iris-setosa
2    4.7  1.3  3.2  0.2     Iris-setosa
3    4.6  1.5  3.1  0.2     Iris-setosa
4    5.0  1.4  3.6  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  5.2  3.0  2.3  Iris-virginica
146  6.3  5.0  2.5  1.9  Iris-virginica
147  6.5  5.2  3.0  2.0  Iris-virginica
148  6.2  5.4  3.4  2.3  Iris-virginica
149  5.9  5.1  3.0  1.8  Iris-virginica

[150 rows x 5 columns]


# Pandas - Delete Columns from DataFrame

# Pandas - Delete Columns from a DataFrame

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('iris.data', names=['A','B','C','D','Label'])
df

       A    B    C    D           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

### 1) to drop a single column
, and saving it permanently df.drop('col_name', axis=1,inplace =True)  
To save changes you must either set df = df.drop(), or add inplace=True.

In [3]:
df.drop('B', axis=1)

       A    C    D           Label
0    5.1  1.4  0.2     Iris-setosa
1    4.9  1.4  0.2     Iris-setosa
2    4.7  1.3  0.2     Iris-setosa
3    4.6  1.5  0.2     Iris-setosa
4    5.0  1.4  0.2     Iris-setosa
..   ...  ...  ...             ...
145  6.7  5.2  2.3  Iris-virginica
146  6.3  5.0  1.9  Iris-virginica
147  6.5  5.2  2.0  Iris-virginica
148  6.2  5.4  2.3  Iris-virginica
149  5.9  5.1  1.8  Iris-virginica

[150 rows x 4 columns]

In [4]:
df

       A    B    C    D           Label
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

### 2) to drop multiple axes by name
df.drop(['col_name1', 'col_name2'], axis=1, inplace=True)

In [5]:
df.drop(['A','Label'], axis=1, inplace=True)
df

       B    C    D
0    3.5  1.4  0.2
1    3.0  1.4  0.2
2    3.2  1.3  0.2
3    3.1  1.5  0.2
4    3.6  1.4  0.2
..   ...  ...  ...
145  3.0  5.2  2.3
146  2.5  5.0  1.9
147  3.0  5.2  2.0
148  3.4  5.4  2.3
149  3.0  5.1  1.8

[150 rows x 3 columns]

### 3) to drop multiple axes by numerical column index
df.drop(df.columns[[idx1, idx2]], axis=1, inplace=True)

In [7]:
df.drop(df.columns[[0, 2]], axis=1, inplace=True)
df

       C
0    1.4
1    1.4
2    1.3
3    1.5
4    1.4
..   ...
145  5.2
146  5.0
147  5.2
148  5.4
149  5.1

[150 rows x 1 columns]


# Pandas - Delete NaN Rows from DataFrame

# Pandas - Delete NaN Rows from DataFrame

[StackOverflow Thread](https://stackoverflow.com/questions/13413590/how-to-drop-rows-of-pandas-dataframe-whose-value-in-a-certain-column-is-nan)

In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame(np.random.randn(12,3))
df

           0         1         2
0  -1.358720 -0.493967  0.258351
1   0.338347  0.498426 -0.050406
2   0.821865 -0.376314 -1.504425
3  -0.551876  0.694595  0.540055
4  -0.493108 -0.570255  0.160218
5  -0.705264 -1.940984  0.321970
6   0.257133  0.642613 -0.416996
7  -1.391762 -1.689991 -1.804575
8   1.459479 -0.731590 -0.061360
9   1.314401 -1.666592 -1.778455
10 -0.353425 -0.654705 -0.155042
11 -0.898696 -0.756802  0.539142

In [4]:
df.iloc[::2,0] = np.nan
df.iloc[::3,1] = np.nan
df.iloc[::4,2] = np.nan
df

           0         1         2
0        NaN       NaN       NaN
1   0.338347  0.498426 -0.050406
2        NaN -0.376314 -1.504425
3  -0.551876       NaN  0.540055
4        NaN -0.570255       NaN
5  -0.705264 -1.940984  0.321970
6        NaN       NaN -0.416996
7  -1.391762 -1.689991 -1.804575
8        NaN -0.731590       NaN
9   1.314401       NaN -1.778455
10       NaN -0.654705 -0.155042
11 -0.898696 -0.756802  0.539142

**- Drop all rows that have *any* NaN values**

In [5]:
df.dropna()

           0         1         2
1   0.338347  0.498426 -0.050406
5  -0.705264 -1.940984  0.321970
7  -1.391762 -1.689991 -1.804575
11 -0.898696 -0.756802  0.539142

**- drop only if *all* columns are NaN**

In [6]:
df.dropna(how='all')

           0         1         2
1   0.338347  0.498426 -0.050406
2        NaN -0.376314 -1.504425
3  -0.551876       NaN  0.540055
4        NaN -0.570255       NaN
5  -0.705264 -1.940984  0.321970
6        NaN       NaN -0.416996
7  -1.391762 -1.689991 -1.804575
8        NaN -0.731590       NaN
9   1.314401       NaN -1.778455
10       NaN -0.654705 -0.155042
11 -0.898696 -0.756802  0.539142

**- Drop only if NaN in a specific column**

In [8]:
df.dropna(subset=[2])

           0         1         2
1   0.338347  0.498426 -0.050406
2        NaN -0.376314 -1.504425
3  -0.551876       NaN  0.540055
5  -0.705264 -1.940984  0.321970
6        NaN       NaN -0.416996
7  -1.391762 -1.689991 -1.804575
9   1.314401       NaN -1.778455
10       NaN -0.654705 -0.155042
11 -0.898696 -0.756802  0.539142


# Pandas - Iterate Rows of a DataFrame

# Pandas - Iterate Rows of a DataFrame

In [1]:
import pandas as pd

In [18]:
df = pd.read_csv('iris.data', header=None)
df

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

### Get a List of one Column
Use a list comprehension.

In [19]:
col2 = [x for x in df[2]]
col2

[1.4,
 1.4,
 1.3,
 1.5,
 1.4,
 1.7,
 1.4,
 1.5,
 1.4,
 1.5,
 1.5,
 1.6,
 1.4,
 1.1,
 1.2,
 1.5,
 1.3,
 1.4,
 1.7,
 1.5,
 1.7,
 1.5,
 1.0,
 1.7,
 1.9,
 1.6,
 1.6,
 1.5,
 1.4,
 1.6,
 1.6,
 1.5,
 1.5,
 1.4,
 1.5,
 1.2,
 1.3,
 1.5,
 1.3,
 1.5,
 1.3,
 1.3,
 1.3,
 1.6,
 1.9,
 1.4,
 1.6,
 1.4,
 1.5,
 1.4,
 4.7,
 4.5,
 4.9,
 4.0,
 4.6,
 4.5,
 4.7,
 3.3,
 4.6,
 3.9,
 3.5,
 4.2,
 4.0,
 4.7,
 3.6,
 4.4,
 4.5,
 4.1,
 4.5,
 3.9,
 4.8,
 4.0,
 4.9,
 4.7,
 4.3,
 4.4,
 4.8,
 5.0,
 4.5,
 3.5,
 3.8,
 3.7,
 3.9,
 5.1,
 4.5,
 4.5,
 4.7,
 4.4,
 4.1,
 4.0,
 4.4,
 4.6,
 4.0,
 3.3,
 4.2,
 4.2,
 4.2,
 4.3,
 3.0,
 4.1,
 6.0,
 5.1,
 5.9,
 5.6,
 5.8,
 6.6,
 4.5,
 6.3,
 5.8,
 6.1,
 5.1,
 5.3,
 5.5,
 5.0,
 5.1,
 5.3,
 5.5,
 6.7,
 6.9,
 5.0,
 5.7,
 4.9,
 6.7,
 4.9,
 5.7,
 6.0,
 4.8,
 4.9,
 5.6,
 5.8,
 6.1,
 6.4,
 5.6,
 5.1,
 5.6,
 6.1,
 5.6,
 5.5,
 4.8,
 5.4,
 5.6,
 5.1,
 5.1,
 5.9,
 5.7,
 5.2,
 5.0,
 5.2,
 5.4,
 5.1]

### Iterate Rows with Index and each Row as a List
**DO NOT** try to change data in the df this way, but it is convenient for iterating.  
Itertuples is supposed to be much faster than Iterrows for large datasets.

In [17]:
for i, row in df.iterrows():
    print(i, row[0], row[1], row[2], row[3], row[4])

0 5.1 3.5 1.4 0.2 Iris-setosa
1 4.9 3.0 1.4 0.2 Iris-setosa
2 4.7 3.2 1.3 0.2 Iris-setosa
3 4.6 3.1 1.5 0.2 Iris-setosa
4 5.0 3.6 1.4 0.2 Iris-setosa
5 5.4 3.9 1.7 0.4 Iris-setosa
6 4.6 3.4 1.4 0.3 Iris-setosa
7 5.0 3.4 1.5 0.2 Iris-setosa
8 4.4 2.9 1.4 0.2 Iris-setosa
9 4.9 3.1 1.5 0.1 Iris-setosa
10 5.4 3.7 1.5 0.2 Iris-setosa
11 4.8 3.4 1.6 0.2 Iris-setosa
12 4.8 3.0 1.4 0.1 Iris-setosa
13 4.3 3.0 1.1 0.1 Iris-setosa
14 5.8 4.0 1.2 0.2 Iris-setosa
15 5.7 4.4 1.5 0.4 Iris-setosa
16 5.4 3.9 1.3 0.4 Iris-setosa
17 5.1 3.5 1.4 0.3 Iris-setosa
18 5.7 3.8 1.7 0.3 Iris-setosa
19 5.1 3.8 1.5 0.3 Iris-setosa
20 5.4 3.4 1.7 0.2 Iris-setosa
21 5.1 3.7 1.5 0.4 Iris-setosa
22 4.6 3.6 1.0 0.2 Iris-setosa
23 5.1 3.3 1.7 0.5 Iris-setosa
24 4.8 3.4 1.9 0.2 Iris-setosa
25 5.0 3.0 1.6 0.2 Iris-setosa
26 5.0 3.4 1.6 0.4 Iris-setosa
27 5.2 3.5 1.5 0.2 Iris-setosa
28 5.2 3.4 1.4 0.2 Iris-setosa
29 4.7 3.2 1.6 0.2 Iris-setosa
30 4.8 3.1 1.6 0.2 Iris-setosa
31 5.4 3.4 1.5 0.4 Iris-setosa
32 5.2 4.1 1.5 0.1 Iris-setosa
33 5.5 4.2 1.4 0.2 Iris-setosa
34 4.9 3.1 1.5 0.1 Iris-setosa
35 5.0 3.2 1.2 0.2 Iris-setosa
36 5.5 3.5 1.3 0.2 Iris-setosa
37 4.9 3.1 1.5 0.1 Iris-setosa
38 4.4 3.0 1.3 0.2 Iris-setosa
39 5.1 3.4 1.5 0.2 Iris-setosa
40 5.0 3.5 1.3 0.3 Iris-setosa
41 4.5 2.3 1.3 0.3 Iris-setosa
42 4.4 3.2 1.3 0.2 Iris-setosa
43 5.0 3.5 1.6 0.6 Iris-setosa
44 5.1 3.8 1.9 0.4 Iris-setosa
45 4.8 3.0 1.4 0.3 Iris-setosa
46 5.1 3.8 1.6 0.2 Iris-setosa
47 4.6 3.2 1.4 0.2 Iris-setosa
48 5.3 3.7 1.5 0.2 Iris-setosa
49 5.0 3.3 1.4 0.2 Iris-setosa
50 7.0 3.2 4.7 1.4 Iris-versicolor
51 6.4 3.2 4.5 1.5 Iris-versicolor
52 6.9 3.1 4.9 1.5 Iris-versicolor
53 5.5 2.3 4.0 1.3 Iris-versicolor
54 6.5 2.8 4.6 1.5 Iris-versicolor
55 5.7 2.8 4.5 1.3 Iris-versicolor
56 6.3 3.3 4.7 1.6 Iris-versicolor
57 4.9 2.4 3.3 1.0 Iris-versicolor
58 6.6 2.9 4.6 1.3 Iris-versicolor
59 5.2 2.7 3.9 1.4 Iris-versicolor
60 5.0 2.0 3.5 1.0 Iris-versicolor
61 5.9 3.0 4.2 1.5 Iris-versicolor
62 6.0 2.2 4.0 1.0 Iris-versicolor
63 6.1 2.9 4.7 1.4 Iris-versicolor
64 5.6 2.9 3.6 1.3 Iris-versicolor
65 6.7 3.1 4.4 1.4 Iris-versicolor
66 5.6 3.0 4.5 1.5 Iris-versicolor
67 5.8 2.7 4.1 1.0 Iris-versicolor
68 6.2 2.2 4.5 1.5 Iris-versicolor
69 5.6 2.5 3.9 1.1 Iris-versicolor
70 5.9 3.2 4.8 1.8 Iris-versicolor
71 6.1 2.8 4.0 1.3 Iris-versicolor
72 6.3 2.5 4.9 1.5 Iris-versicolor
73 6.1 2.8 4.7 1.2 Iris-versicolor
74 6.4 2.9 4.3 1.3 Iris-versicolor
75 6.6 3.0 4.4 1.4 Iris-versicolor
76 6.8 2.8 4.8 1.4 Iris-versicolor
77 6.7 3.0 5.0 1.7 Iris-versicolor
78 6.0 2.9 4.5 1.5 Iris-versicolor
79 5.7 2.6 3.5 1.0 Iris-versicolor
80 5.5 2.4 3.8 1.1 Iris-versicolor
81 5.5 2.4 3.7 1.0 Iris-versicolor
82 5.8 2.7 3.9 1.2 Iris-versicolor
83 6.0 2.7 5.1 1.6 Iris-versicolor
84 5.4 3.0 4.5 1.5 Iris-versicolor
85 6.0 3.4 4.5 1.6 Iris-versicolor
86 6.7 3.1 4.7 1.5 Iris-versicolor
87 6.3 2.3 4.4 1.3 Iris-versicolor
88 5.6 3.0 4.1 1.3 Iris-versicolor
89 5.5 2.5 4.0 1.3 Iris-versicolor
90 5.5 2.6 4.4 1.2 Iris-versicolor
91 6.1 3.0 4.6 1.4 Iris-versicolor
92 5.8 2.6 4.0 1.2 Iris-versicolor
93 5.0 2.3 3.3 1.0 Iris-versicolor
94 5.6 2.7 4.2 1.3 Iris-versicolor
95 5.7 3.0 4.2 1.2 Iris-versicolor
96 5.7 2.9 4.2 1.3 Iris-versicolor
97 6.2 2.9 4.3 1.3 Iris-versicolor
98 5.1 2.5 3.0 1.1 Iris-versicolor
99 5.7 2.8 4.1 1.3 Iris-versicolor
100 6.3 3.3 6.0 2.5 Iris-virginica
101 5.8 2.7 5.1 1.9 Iris-virginica
102 7.1 3.0 5.9 2.1 Iris-virginica
103 6.3 2.9 5.6 1.8 Iris-virginica
104 6.5 3.0 5.8 2.2 Iris-virginica
105 7.6 3.0 6.6 2.1 Iris-virginica
106 4.9 2.5 4.5 1.7 Iris-virginica
107 7.3 2.9 6.3 1.8 Iris-virginica
108 6.7 2.5 5.8 1.8 Iris-virginica
109 7.2 3.6 6.1 2.5 Iris-virginica
110 6.5 3.2 5.1 2.0 Iris-virginica
111 6.4 2.7 5.3 1.9 Iris-virginica
112 6.8 3.0 5.5 2.1 Iris-virginica
113 5.7 2.5 5.0 2.0 Iris-virginica
114 5.8 2.8 5.1 2.4 Iris-virginica
115 6.4 3.2 5.3 2.3 Iris-virginica
116 6.5 3.0 5.5 1.8 Iris-virginica
117 7.7 3.8 6.7 2.2 Iris-virginica
118 7.7 2.6 6.9 2.3 Iris-virginica
119 6.0 2.2 5.0 1.5 Iris-virginica
120 6.9 3.2 5.7 2.3 Iris-virginica
121 5.6 2.8 4.9 2.0 Iris-virginica
122 7.7 2.8 6.7 2.0 Iris-virginica
123 6.3 2.7 4.9 1.8 Iris-virginica
124 6.7 3.3 5.7 2.1 Iris-virginica
125 7.2 3.2 6.0 1.8 Iris-virginica
126 6.2 2.8 4.8 1.8 Iris-virginica
127 6.1 3.0 4.9 1.8 Iris-virginica
128 6.4 2.8 5.6 2.1 Iris-virginica
129 7.2 3.0 5.8 1.6 Iris-virginica
130 7.4 2.8 6.1 1.9 Iris-virginica
131 7.9 3.8 6.4 2.0 Iris-virginica
132 6.4 2.8 5.6 2.2 Iris-virginica
133 6.3 2.8 5.1 1.5 Iris-virginica
134 6.1 2.6 5.6 1.4 Iris-virginica
135 7.7 3.0 6.1 2.3 Iris-virginica
136 6.3 3.4 5.6 2.4 Iris-virginica
137 6.4 3.1 5.5 1.8 Iris-virginica
138 6.0 3.0 4.8 1.8 Iris-virginica
139 6.9 3.1 5.4 2.1 Iris-virginica
140 6.7 3.1 5.6 2.4 Iris-virginica
141 6.9 3.1 5.1 2.3 Iris-virginica
142 5.8 2.7 5.1 1.9 Iris-virginica
143 6.8 3.2 5.9 2.3 Iris-virginica
144 6.7 3.3 5.7 2.5 Iris-virginica
145 6.7 3.0 5.2 2.3 Iris-virginica
146 6.3 2.5 5.0 1.9 Iris-virginica
147 6.5 3.0 5.2 2.0 Iris-virginica
148 6.2 3.4 5.4 2.3 Iris-virginica
149 5.9 3.0 5.1 1.8 Iris-virginica

In [16]:
for row in df.itertuples(name=None): 
    print(row[0], row[1], row[2], row[3], row[4], row[5])

0 5.1 3.5 1.4 0.2 Iris-setosa
1 4.9 3.0 1.4 0.2 Iris-setosa
2 4.7 3.2 1.3 0.2 Iris-setosa
3 4.6 3.1 1.5 0.2 Iris-setosa
4 5.0 3.6 1.4 0.2 Iris-setosa
5 5.4 3.9 1.7 0.4 Iris-setosa
6 4.6 3.4 1.4 0.3 Iris-setosa
7 5.0 3.4 1.5 0.2 Iris-setosa
8 4.4 2.9 1.4 0.2 Iris-setosa
9 4.9 3.1 1.5 0.1 Iris-setosa
10 5.4 3.7 1.5 0.2 Iris-setosa
11 4.8 3.4 1.6 0.2 Iris-setosa
12 4.8 3.0 1.4 0.1 Iris-setosa
13 4.3 3.0 1.1 0.1 Iris-setosa
14 5.8 4.0 1.2 0.2 Iris-setosa
15 5.7 4.4 1.5 0.4 Iris-setosa
16 5.4 3.9 1.3 0.4 Iris-setosa
17 5.1 3.5 1.4 0.3 Iris-setosa
18 5.7 3.8 1.7 0.3 Iris-setosa
19 5.1 3.8 1.5 0.3 Iris-setosa
20 5.4 3.4 1.7 0.2 Iris-setosa
21 5.1 3.7 1.5 0.4 Iris-setosa
22 4.6 3.6 1.0 0.2 Iris-setosa
23 5.1 3.3 1.7 0.5 Iris-setosa
24 4.8 3.4 1.9 0.2 Iris-setosa
25 5.0 3.0 1.6 0.2 Iris-setosa
26 5.0 3.4 1.6 0.4 Iris-setosa
27 5.2 3.5 1.5 0.2 Iris-setosa
28 5.2 3.4 1.4 0.2 Iris-setosa
29 4.7 3.2 1.6 0.2 Iris-setosa
30 4.8 3.1 1.6 0.2 Iris-setosa
31 5.4 3.4 1.5 0.4 Iris-setosa
32 5.2 4.1 1.5 0.1 Iris-setosa
33 5.5 4.2 1.4 0.2 Iris-setosa
34 4.9 3.1 1.5 0.1 Iris-setosa
35 5.0 3.2 1.2 0.2 Iris-setosa
36 5.5 3.5 1.3 0.2 Iris-setosa
37 4.9 3.1 1.5 0.1 Iris-setosa
38 4.4 3.0 1.3 0.2 Iris-setosa
39 5.1 3.4 1.5 0.2 Iris-setosa
40 5.0 3.5 1.3 0.3 Iris-setosa
41 4.5 2.3 1.3 0.3 Iris-setosa
42 4.4 3.2 1.3 0.2 Iris-setosa
43 5.0 3.5 1.6 0.6 Iris-setosa
44 5.1 3.8 1.9 0.4 Iris-setosa
45 4.8 3.0 1.4 0.3 Iris-setosa
46 5.1 3.8 1.6 0.2 Iris-setosa
47 4.6 3.2 1.4 0.2 Iris-setosa
48 5.3 3.7 1.5 0.2 Iris-setosa
49 5.0 3.3 1.4 0.2 Iris-setosa
50 7.0 3.2 4.7 1.4 Iris-versicolor
51 6.4 3.2 4.5 1.5 Iris-versicolor
52 6.9 3.1 4.9 1.5 Iris-versicolor
53 5.5 2.3 4.0 1.3 Iris-versicolor
54 6.5 2.8 4.6 1.5 Iris-versicolor
55 5.7 2.8 4.5 1.3 Iris-versicolor
56 6.3 3.3 4.7 1.6 Iris-versicolor
57 4.9 2.4 3.3 1.0 Iris-versicolor
58 6.6 2.9 4.6 1.3 Iris-versicolor
59 5.2 2.7 3.9 1.4 Iris-versicolor
60 5.0 2.0 3.5 1.0 Iris-versicolor
61 5.9 3.0 4.2 1.5 Iris-versicolor
62 6.0 2.2 4.0 1.0 Iris-versicolor
63 6.1 2.9 4.7 1.4 Iris-versicolor
64 5.6 2.9 3.6 1.3 Iris-versicolor
65 6.7 3.1 4.4 1.4 Iris-versicolor
66 5.6 3.0 4.5 1.5 Iris-versicolor
67 5.8 2.7 4.1 1.0 Iris-versicolor
68 6.2 2.2 4.5 1.5 Iris-versicolor
69 5.6 2.5 3.9 1.1 Iris-versicolor
70 5.9 3.2 4.8 1.8 Iris-versicolor
71 6.1 2.8 4.0 1.3 Iris-versicolor
72 6.3 2.5 4.9 1.5 Iris-versicolor
73 6.1 2.8 4.7 1.2 Iris-versicolor
74 6.4 2.9 4.3 1.3 Iris-versicolor
75 6.6 3.0 4.4 1.4 Iris-versicolor
76 6.8 2.8 4.8 1.4 Iris-versicolor
77 6.7 3.0 5.0 1.7 Iris-versicolor
78 6.0 2.9 4.5 1.5 Iris-versicolor
79 5.7 2.6 3.5 1.0 Iris-versicolor
80 5.5 2.4 3.8 1.1 Iris-versicolor
81 5.5 2.4 3.7 1.0 Iris-versicolor
82 5.8 2.7 3.9 1.2 Iris-versicolor
83 6.0 2.7 5.1 1.6 Iris-versicolor
84 5.4 3.0 4.5 1.5 Iris-versicolor
85 6.0 3.4 4.5 1.6 Iris-versicolor
86 6.7 3.1 4.7 1.5 Iris-versicolor
87 6.3 2.3 4.4 1.3 Iris-versicolor
88 5.6 3.0 4.1 1.3 Iris-versicolor
89 5.5 2.5 4.0 1.3 Iris-versicolor
90 5.5 2.6 4.4 1.2 Iris-versicolor
91 6.1 3.0 4.6 1.4 Iris-versicolor
92 5.8 2.6 4.0 1.2 Iris-versicolor
93 5.0 2.3 3.3 1.0 Iris-versicolor
94 5.6 2.7 4.2 1.3 Iris-versicolor
95 5.7 3.0 4.2 1.2 Iris-versicolor
96 5.7 2.9 4.2 1.3 Iris-versicolor
97 6.2 2.9 4.3 1.3 Iris-versicolor
98 5.1 2.5 3.0 1.1 Iris-versicolor
99 5.7 2.8 4.1 1.3 Iris-versicolor
100 6.3 3.3 6.0 2.5 Iris-virginica
101 5.8 2.7 5.1 1.9 Iris-virginica
102 7.1 3.0 5.9 2.1 Iris-virginica
103 6.3 2.9 5.6 1.8 Iris-virginica
104 6.5 3.0 5.8 2.2 Iris-virginica
105 7.6 3.0 6.6 2.1 Iris-virginica
106 4.9 2.5 4.5 1.7 Iris-virginica
107 7.3 2.9 6.3 1.8 Iris-virginica
108 6.7 2.5 5.8 1.8 Iris-virginica
109 7.2 3.6 6.1 2.5 Iris-virginica
110 6.5 3.2 5.1 2.0 Iris-virginica
111 6.4 2.7 5.3 1.9 Iris-virginica
112 6.8 3.0 5.5 2.1 Iris-virginica
113 5.7 2.5 5.0 2.0 Iris-virginica
114 5.8 2.8 5.1 2.4 Iris-virginica
115 6.4 3.2 5.3 2.3 Iris-virginica
116 6.5 3.0 5.5 1.8 Iris-virginica
117 7.7 3.8 6.7 2.2 Iris-virginica
118 7.7 2.6 6.9 2.3 Iris-virginica
119 6.0 2.2 5.0 1.5 Iris-virginica
120 6.9 3.2 5.7 2.3 Iris-virginica
121 5.6 2.8 4.9 2.0 Iris-virginica
122 7.7 2.8 6.7 2.0 Iris-virginica
123 6.3 2.7 4.9 1.8 Iris-virginica
124 6.7 3.3 5.7 2.1 Iris-virginica
125 7.2 3.2 6.0 1.8 Iris-virginica
126 6.2 2.8 4.8 1.8 Iris-virginica
127 6.1 3.0 4.9 1.8 Iris-virginica
128 6.4 2.8 5.6 2.1 Iris-virginica
129 7.2 3.0 5.8 1.6 Iris-virginica
130 7.4 2.8 6.1 1.9 Iris-virginica
131 7.9 3.8 6.4 2.0 Iris-virginica
132 6.4 2.8 5.6 2.2 Iris-virginica
133 6.3 2.8 5.1 1.5 Iris-virginica
134 6.1 2.6 5.6 1.4 Iris-virginica
135 7.7 3.0 6.1 2.3 Iris-virginica
136 6.3 3.4 5.6 2.4 Iris-virginica
137 6.4 3.1 5.5 1.8 Iris-virginica
138 6.0 3.0 4.8 1.8 Iris-virginica
139 6.9 3.1 5.4 2.1 Iris-virginica
140 6.7 3.1 5.6 2.4 Iris-virginica
141 6.9 3.1 5.1 2.3 Iris-virginica
142 5.8 2.7 5.1 1.9 Iris-virginica
143 6.8 3.2 5.9 2.3 Iris-virginica
144 6.7 3.3 5.7 2.5 Iris-virginica
145 6.7 3.0 5.2 2.3 Iris-virginica
146 6.3 2.5 5.0 1.9 Iris-virginica
147 6.5 3.0 5.2 2.0 Iris-virginica
148 6.2 3.4 5.4 2.3 Iris-virginica
149 5.9 3.0 5.1 1.8 Iris-virginica


# Python Pandas Time Series Data

# Python Pandas Time Series Data
[Documentation](https://pandas.pydata.org/docs/user_guide/timeseries.html)

In [1]:
import numpy as np
import pandas as pd
import datetime
import random

### Data Formats Supported
Pandas datetime64 can interpret strings, Python datetime, and Numpy datetime64 objects.  
Also note, a list of pd.datetime64 objects are automatically converted to a DatetimeIndex.

In [2]:
a1 = pd.to_datetime([
    '6/1/2020', 
    '6-2-2020',
    datetime.datetime(2020, 6, 3),
    np.datetime64('2020-06-04'),
    np.datetime64('2020-06-05')])
a1

DatetimeIndex(['2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05'],
              dtype='datetime64[ns]', freq=None)

Pass in a format argument for custom formatted dates (case matters).

In [3]:
a2 = pd.to_datetime(['2020/14/06', '2020/15/06'], format='%Y/%d/%m')
a2

DatetimeIndex(['2020-06-14', '2020-06-15'], dtype='datetime64[ns]', freq=None)

Hours and Minutes too? No problem.

In [4]:
a3 = pd.to_datetime(
    ['2020/6/8 14.05', '2020/6/9 06.45'], format='%Y/%d/%m %H.%M')
a3

DatetimeIndex(['2020-08-06 14:05:00', '2020-09-06 06:45:00'], dtype='datetime64[ns]', freq=None)

### Creating a datetime sequence with fixed intervals
freq parameters:  
  D=days, W=weeks, M=months, B=business days, BW=bus weeks, BM=bus months

In [5]:
b1 = [random.random() for i in range(30)]
b2 = pd.date_range('2020-06-01', periods=30, freq='1d')
print(b2)
df = pd.DataFrame({'M':b1}, index=b2)
#df.loc['2020-06-18':]
df[df['M'] > 0.8]

DatetimeIndex(['2020-06-01', '2020-06-02', '2020-06-03', '2020-06-04',
               '2020-06-05', '2020-06-06', '2020-06-07', '2020-06-08',
               '2020-06-09', '2020-06-10', '2020-06-11', '2020-06-12',
               '2020-06-13', '2020-06-14', '2020-06-15', '2020-06-16',
               '2020-06-17', '2020-06-18', '2020-06-19', '2020-06-20',
               '2020-06-21', '2020-06-22', '2020-06-23', '2020-06-24',
               '2020-06-25', '2020-06-26', '2020-06-27', '2020-06-28',
               '2020-06-29', '2020-06-30'],
              dtype='datetime64[ns]', freq='D')

                   M
2020-06-07  0.970080
2020-06-14  0.809867
2020-06-18  0.917428
2020-06-20  0.945739
2020-06-26  0.815245

In [61]:
b3 = np.random.rand(52)
b4 = pd.date_range('2020-06-01', periods=52, freq='W')
df = pd.DataFrame(b3, index=b4)
df['2020-07-10':'2020-07-28']

                   0
2020-07-12  0.581691
2020-07-19  0.611492
2020-07-26  0.933940

Alternative to periods, you can give start and stop dates.

In [7]:
b3 = pd.date_range('2020-06-30', '2020-12-31', freq='M')
b3

DatetimeIndex(['2020-06-30', '2020-07-31', '2020-08-31', '2020-09-30',
               '2020-10-31', '2020-11-30', '2020-12-31'],
              dtype='datetime64[ns]', freq='M')

### Dates Index to/from CSV file
Create DataFrame with Dates as Index, Write it to a CSV file, then Read in the CSV data and put the dates as Index

In [8]:
d1 = np.round(6 + 4 * np.random.randn(7), decimals=2)
d2 = np.random.randint(12, 30, size=7)
d3 = pd.Series(pd.date_range('2020-05-29', periods=7, freq='1d'))
df = pd.DataFrame({'alpha':d1, 'beta':d2}, index=d3)

df.to_csv('file01.csv')
df

            alpha  beta
2020-05-29  10.40    26
2020-05-30   8.92    26
2020-05-31   5.09    12
2020-06-01   3.87    27
2020-06-02   3.93    24
2020-06-03   4.79    16
2020-06-04   9.12    16

In [63]:
df = pd.read_csv('file01.csv', index_col=0)
print(type(df.index[2]))
df.index = pd.to_datetime(df.index, format='%Y/%m/%d')
print(type(df.index[2]))
df[:'2020/05/31']

<class 'str'>
<class 'pandas._libs.tslibs.timestamps.Timestamp'>

            alpha  beta
2020-05-29  10.40    26
2020-05-30   8.92    26
2020-05-31   5.09    12

### Constructing Dates from Multiple Columns
You have Month, Day and Year in separate fields, and need to combine them into a single Datetime field.

In [25]:
yyyy = [random.randint(1995,2020) for i in range(100)]
mm = [random.randint(1,12) for i in range(100)]
dd = [random.randint(1,28) for i in range(100)]
data = [random.random() for i in range(100)]
print(yyyy[5], mm[5], dd[5], data[5])

2017 12 7 0.970109923902562

In [64]:
df1 = pd.DataFrame({'year': yyyy,'month': mm, 'day': dd})
df1 = pd.to_datetime(df1) 
df2 = pd.Series(data)
df = pd.concat([df1, df2], axis=1)
df[:5]

           0         1
0 2016-10-18  0.282307
1 2007-09-09  0.004984
2 2016-12-12  0.652762
3 2017-04-14  0.199284
4 2013-03-23  0.163154

### Pivot (Transpose) Rows & Columns
You normally want dates as the row index, not the column headers.  
Flip the rows and columns using T.

In [57]:
df = pd.read_csv('pivot.csv')
df = df.T
df.head()

                            0
2016-10-18 00:00:00  0.282307
2007-09-09 00:00:00  0.004984
2016-12-12 00:00:00  0.652762
2017-04-14 00:00:00  0.199284
2013-03-23 00:00:00  0.163154

### Date Arithmetic

In [12]:
appointment = pd.Timestamp('2020-06-04')
appointment.day_name()

'Thursday'

Uh oh! my appointment is delayed 2 days.  
Here are 3 different ways to add 2 days to the date.

In [13]:
appointment = pd.Timestamp('2020-06-04')
appointment += pd.Timedelta('2 days')
appointment.day_name()

'Saturday'

In [14]:
appointment = pd.Timestamp('2020-06-04')
appointment += pd.Timedelta(days=2)
appointment.day_name()

'Saturday'

Date offsets: Day, Hour, Minute, Second, Milli, Micro, Nano

In [15]:
appointment = pd.Timestamp('2020-06-04')
appointment += pd.offsets.Day(2)
appointment.day_name()

'Saturday'

NO, it's delayed 2 business days.

In [16]:
appointment = pd.Timestamp('2020-06-04')
appointment += pd.offsets.BDay(2)
appointment.day_name()

'Monday'